name: flutter_google_calendar_sample_app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1
  intl: ^0.17.0
  syncfusion_flutter_calendar: ^20.4.53

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  pedantic_mono:

flutter:
  uses-material-design: true
